import UIKit
import PDFKit

struct PDFReportService {

    static func generateReport(for audit: Audit) -> Data {
        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 50
        let contentWidth = pageWidth - margin * 2

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        let data = renderer.pdfData { context in
            var yPosition: CGFloat = 0

            func startNewPage() {
                context.beginPage()
                yPosition = margin
            }

            func ensureSpace(_ needed: CGFloat) {
                if yPosition + needed > pageHeight - margin {
                    startNewPage()
                }
            }

            func drawText(_ text: String, font: UIFont, color: UIColor = .label, maxWidth: CGFloat = contentWidth) -> CGFloat {
                let paragraphStyle = NSMutableParagraphStyle()
                paragraphStyle.lineSpacing = 2
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color,
                    .paragraphStyle: paragraphStyle
                ]
                let rect = CGRect(x: margin, y: yPosition, width: maxWidth, height: .greatestFiniteMagnitude)
                let boundingRect = (text as NSString).boundingRect(with: CGSize(width: maxWidth, height: .greatestFiniteMagnitude),
                                                                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                                                                    attributes: attrs, context: nil)
                (text as NSString).draw(in: CGRect(x: margin, y: yPosition, width: maxWidth, height: boundingRect.height), withAttributes: attrs)
                let height = ceil(boundingRect.height)
                yPosition += height
                return height
            }

            func drawDivider() {
                ensureSpace(20)
                let path = UIBezierPath()
                path.move(to: CGPoint(x: margin, y: yPosition + 8))
                path.addLine(to: CGPoint(x: pageWidth - margin, y: yPosition + 8))
                UIColor.separator.setStroke()
                path.lineWidth = 0.5
                path.stroke()
                yPosition += 16
            }

            func drawSeverityDot(color: UIColor, x: CGFloat, y: CGFloat) {
                let dotRect = CGRect(x: x, y: y + 3, width: 8, height: 8)
                let path = UIBezierPath(ovalIn: dotRect)
                color.setFill()
                path.fill()
            }

            // MARK: - Cover Page
            startNewPage()
            yPosition = pageHeight * 0.3

            _ = drawText("Accessibility", font: .systemFont(ofSize: 32, weight: .bold), color: .label)
            yPosition += 2
            _ = drawText("Audit Report", font: .systemFont(ofSize: 32, weight: .bold), color: .label)
            yPosition += 24

            drawDivider()
            yPosition += 8

            _ = drawText(audit.appName, font: .systemFont(ofSize: 20, weight: .medium), color: .secondaryLabel)
            yPosition += 4
            _ = drawText(audit.name, font: .systemFont(ofSize: 14), color: .secondaryLabel)
            yPosition += 16

            if !audit.auditorName.isEmpty {
                _ = drawText("Auditor: \(audit.auditorName)", font: .systemFont(ofSize: 12), color: .tertiaryLabel)
                yPosition += 4
            }
            _ = drawText("Platform: \(audit.platform.displayName)", font: .systemFont(ofSize: 12), color: .tertiaryLabel)
            yPosition += 4

            let formatter = DateFormatter()
            formatter.dateStyle = .long
            _ = drawText("Date: \(formatter.string(from: audit.createdDate))", font: .systemFont(ofSize: 12), color: .tertiaryLabel)
            yPosition += 4
            _ = drawText("Generated by ARIA", font: .systemFont(ofSize: 10), color: .quaternaryLabel)

            // MARK: - Summary Page
            startNewPage()
            _ = drawText("Executive Summary", font: .systemFont(ofSize: 22, weight: .bold))
            yPosition += 16

            _ = drawText("Total findings: \(audit.totalFindings)", font: .systemFont(ofSize: 14, weight: .medium))
            yPosition += 4
            _ = drawText("Screens audited: \(audit.screens.count)", font: .systemFont(ofSize: 14, weight: .medium))
            yPosition += 16

            let severities: [(String, Int, UIColor)] = [
                ("Critical", audit.criticalCount, UIColor(red: 220/255, green: 38/255, blue: 38/255, alpha: 1)),
                ("Major", audit.majorCount, UIColor(red: 234/255, green: 88/255, blue: 12/255, alpha: 1)),
                ("Moderate", audit.moderateCount, UIColor(red: 202/255, green: 138/255, blue: 4/255, alpha: 1)),
                ("Minor", audit.minorCount, UIColor(red: 100/255, green: 116/255, blue: 139/255, alpha: 1)),
            ]

            for (label, count, color) in severities {
                ensureSpace(24)
                drawSeverityDot(color: color, x: margin, y: yPosition)
                let saved = yPosition
                let xOffset: CGFloat = margin + 16
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.systemFont(ofSize: 13, weight: .medium),
                    .foregroundColor: UIColor.label
                ]
                let text = "\(count) \(label)"
                (text as NSString).draw(at: CGPoint(x: xOffset, y: saved), withAttributes: attrs)
                yPosition = saved + 20
            }

            drawDivider()

            // MARK: - Findings by Screen
            for screen in audit.sortedScreens {
                ensureSpace(60)
                _ = drawText(screen.name, font: .systemFont(ofSize: 18, weight: .semibold))
                yPosition += 4
                _ = drawText("\(screen.findings.count) finding\(screen.findings.count == 1 ? "" : "s")",
                             font: .systemFont(ofSize: 11), color: .secondaryLabel)
                yPosition += 12

                for finding in screen.sortedFindings {
                    ensureSpace(80)

                    let severityColor: UIColor
                    switch finding.severity {
                    case .critical: severityColor = UIColor(red: 220/255, green: 38/255, blue: 38/255, alpha: 1)
                    case .major: severityColor = UIColor(red: 234/255, green: 88/255, blue: 12/255, alpha: 1)
                    case .moderate: severityColor = UIColor(red: 202/255, green: 138/255, blue: 4/255, alpha: 1)
                    case .minor: severityColor = UIColor(red: 100/255, green: 116/255, blue: 139/255, alpha: 1)
                    }

                    drawSeverityDot(color: severityColor, x: margin, y: yPosition)

                    let headerX = margin + 16
                    var headerText = finding.severity.displayName
                    if !finding.wcagCriterionID.isEmpty {
                        headerText += "  ·  \(finding.wcagCriterionID)"
                        if let criterion = WCAGDatabase.criterion(for: finding.wcagCriterionID) {
                            headerText += " \(criterion.name)"
                        }
                    }
                    if finding.isFixed {
                        headerText += "  ✓ Fixed"
                    }

                    let headerAttrs: [NSAttributedString.Key: Any] = [
                        .font: UIFont.systemFont(ofSize: 11, weight: .semibold),
                        .foregroundColor: severityColor
                    ]
                    (headerText as NSString).draw(at: CGPoint(x: headerX, y: yPosition), withAttributes: headerAttrs)
                    yPosition += 18

                    if !finding.findingDescription.isEmpty {
                        let savedX = margin + 16
                        let descWidth = contentWidth - 16
                        let descAttrs: [NSAttributedString.Key: Any] = [
                            .font: UIFont.systemFont(ofSize: 11),
                            .foregroundColor: UIColor.label
                        ]
                        let descRect = (finding.findingDescription as NSString).boundingRect(
                            with: CGSize(width: descWidth, height: .greatestFiniteMagnitude),
                            options: [.usesLineFragmentOrigin],
                            attributes: descAttrs, context: nil)
                        (finding.findingDescription as NSString).draw(
                            in: CGRect(x: savedX, y: yPosition, width: descWidth, height: ceil(descRect.height)),
                            withAttributes: descAttrs)
                        yPosition += ceil(descRect.height) + 4
                    }

                    if !finding.recommendation.isEmpty {
                        let recX = margin + 16
                        let recWidth = contentWidth - 16
                        let recAttrs: [NSAttributedString.Key: Any] = [
                            .font: UIFont.italicSystemFont(ofSize: 10),
                            .foregroundColor: UIColor.secondaryLabel
                        ]
                        let prefix = "Recommendation: "
                        let fullRec = prefix + finding.recommendation
                        let recRect = (fullRec as NSString).boundingRect(
                            with: CGSize(width: recWidth, height: .greatestFiniteMagnitude),
                            options: [.usesLineFragmentOrigin],
                            attributes: recAttrs, context: nil)
                        (fullRec as NSString).draw(
                            in: CGRect(x: recX, y: yPosition, width: recWidth, height: ceil(recRect.height)),
                            withAttributes: recAttrs)
                        yPosition += ceil(recRect.height) + 4
                    }

                    yPosition += 12
                }

                drawDivider()
            }

            // MARK: - Footer on last page
            ensureSpace(40)
            yPosition = pageHeight - margin - 20
            _ = drawText("Generated by ARIA · Mobile Accessibility Audit Tool",
                         font: .systemFont(ofSize: 9), color: .tertiaryLabel)
        }

        return data
    }
}
